default: &default
  adapter: postgresql
  host: localhost
  database: imperium
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  timeout: 10000

development:
  <<: *default
  database: imperium_development

test:
  <<: *default
  database: imperium_test

production:
  <<: *default
  database: imperium_production